uint8 TYPE_CLEAN=0
uint8 TYPE_DEADHEAD=1
uint8 TYPE_TURN_IN_PLACE=2
uint8 TYPE_APPROACH_BRIDGE=3
uint8 TYPE_BRIDGE_CROSSING=4
uint8 TYPE_REINIT_VISION=5

uint8 type
bool brush_on

uint32 block_id
int32 cell_row
int32 cell_col
int32 inner_row
int32 inner_col

uint8 HEADING_BLOCK_U_POSITIVE=0
uint8 HEADING_BLOCK_U_NEGATIVE=1
uint8 HEADING_BLOCK_V_POSITIVE=2
uint8 HEADING_BLOCK_V_NEGATIVE=3
uint8 heading

uint32 bridge_id
int32 rotation_angle_deg
